const IMAGE_SELECTED = "IMAGE_SELECTED";
const GOT_IMAGE_REF = "GOT_IMAGE_REF";
const IMAGE_ADDED = "IMAGE_ADDED";
const CURRENT_MONTH_REF = "CURRENT_MONTH_REF";

export { IMAGE_SELECTED, GOT_IMAGE_REF, IMAGE_ADDED, CURRENT_MONTH_REF };
